### PR TITLE
Add message option to cli

### PR DESCRIPTION
**Pull request by markdalgleish**
I've got this working in another project of mine, it works great: https://github.com/css-modules/webpack-demo

### CODE REVIEW

**Comment by markdalgleish** [comment]
By the way, I'm marked as a collaborator to the `gh-pages` npm package, but not this repo. Could I get collaborator access? I'd be keen to merge this in and bump the version myself.

**Comment by amercier** [comment]
:+1:

**Comment by clkao** [comment]
:+1:

**Comment by tschaub** [comment]
Hey @markdalgleish - I missed this until now.  Should be a quick rebase to fix conflicts.  I added you as a collaborator as well.  Please merge.

**Comment by markdalgleish** [comment]
I've updated my PR, but the Travis build is failing on Node v0.8 for this reason: https://github.com/npm/npm/issues/9668 — the v0.10 build is fine.

I haven't got time to look into a fix right now, but I'd question whether we still want to run tests on Node 0.8 at all, considering Node v4 is out.

**Comment by tschaub** [comment]
I merged in this commit with #39 and published as `gh-pages@0.8.0`.  Thanks @markdalgleish.

We're only testing Node 4 on Travis now (and more test coverage is needed).

**Pull request closed without merging**
