### PR TITLE
cli: add `--no-history` flag not to preserve deploy history

### PR DESCRIPTION
**Pull request by dplusic**
Implemented with reference to `keep-history` of [Travis GitHub Pages Deployment](https://docs.travis-ci.com/user/deployment/pages/).

### CODE REVIEW

**Comment by dplusic** [comment]
@tschaub Would you please review this PR?

**Comment by tschaub** [comment]
Thanks @dplusic!

**Comment by dplusic** [comment]
Thank you @tschaub !

**Comment by tschaub** [comment]
Published with `gh-pages@2.2.0`.

**Pull request merged**
