### PR TITLE
Using stdout instead of stderr to signal success

### LINKED ISSUE #221: Command executed with exception: Published
Hi, using the command line utility from AppVeyor CI, the publish succeeds but I'm getting an error:

```
gh-pages : Published
At line:10 char:5
+     gh-pages -d Docs\_site -m "CI Docs Updates"
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Published:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Command executed with exception: Published
```

Looking at the code, I'm guessing the problem is that you write the "Published" message to stderr and not stdout: 

https://github.com/tschaub/gh-pages/blob/ec1736a6a2cc6f9a3eec738ac05146f0e3f3e232/bin/gh-pages#L65

Full Appveyor log: https://ci.appveyor.com/project/tzachshabtay/monoags/build/1.0.383/job/gxm2yqmkeg996nu1

Appveyor script that triggers the error:
https://github.com/tzachshabtay/MonoAGS/blob/master/appveyor.yml

### PR DESCRIPTION
**Pull request by tzachshabtay**
Hopefully this will resolve #221

### CODE REVIEW

**Comment by tzachshabtay** [comment]
@tschaub can this be merged?
Thanks.

**Comment by tzachshabtay** [comment]
@tschaub bumping, any reason why this can't be merged?
Thanks.

**Comment by sunghwan2789** [comment]
This is merged silently through #264.

**Comment by tschaub** [comment]
Thanks for the proposed change, @tzachshabtay.  I agree with @sunghwan2789 that this is resolved by #264.

**Pull request closed without merging**
