### PR TITLE
support '--git' CLI option

### PR DESCRIPTION
**Pull request by JRJurman**
## Summary

This PR is based #23 to enable the '--git' so we can set the path to git.

### CODE REVIEW

**Comment by JRJurman** [comment]
@tschaub Anything that needs to happen before we can merge this in? I'm happy to do more since this is an ask from my current team from using the tool.

**Comment by tschaub** [comment]
Test added in 5bcf21737c4bb739c0cec295e943e48e235e3242 and released in `gh-pages@2.1.0`.   Thanks for the contribution @JRJurman.

**Comment by kristenbrann** [comment]
@tschaub Thanks for getting this change in! Any idea when `gh-pages@2.1.0` will be released? It's not found when I trying to install via npm, and the npm project page still says 2.0.1.

**Comment by JRJurman** [comment]
@tschaub I'm also noticing this, any updates?

**Comment by tschaub** [comment]
Ack.  https://www.npmjs.com/package/gh-pages/v/2.1.0 is up now.

**Pull request merged**
