### PR TITLE
security(deps): bump filenamify-url to 2.1.1

### PR DESCRIPTION
**Pull request by AviVahl**
regenerated lock file from scratch to get back to 0 vulnerabilities

fixes:
```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ normalize-url                                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.5.1 <5.0.0 || >=5.3.1 <6.0.0 || >=6.0.1                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ gh-pages                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ gh-pages > filenamify-url > humanize-url > normalize-url     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1755                            │
└───────────────┴──────────────────────────────────────────────────────────────┘
```

### CODE REVIEW

**Review by TyMick — APPROVED** [review]
For what it's worth, the only [breaking change in filenamify-url v2](https://github.com/sindresorhus/filenamify-url/releases/tag/v2.0.0) is that it requires Node.js 8, so no other code changes should be necessary. 👍🏼

**Comment by TyMick** [comment]
Though I'm not sure that regenerating the lockfile was necessary—`npm install filenamify-url@2` probably would've been sufficient to upgrade normalize-url.

**Comment by AviVahl** [comment]
> Though I'm not sure that regenerating the lockfile was necessary—`npm install filenamify-url@2` probably would've been sufficient to upgrade normalize-url.

There were other audit failures from locked deps.

**Comment by emilbader** [comment]
Related issue: https://github.com/sindresorhus/filenamify-url/issues/9
Related commit in `humanize-url`: https://github.com/sindresorhus/humanize-url/commit/d013ec7c65c1b5bfa522b18a1f0d3762bfc05d6b

**Comment by AviVahl** [comment]
heya @tschaub, any chance you've got time to review this? :)

**Comment by tschaub** [comment]
Thanks, @AviVahl.

There are automated security updates configured for this repo, but they can take up to 7 days from the time of an alert.  The alert for `filenamify-url` was still only 6 days old.

**Comment by skratchdot** [comment]
I think this change broke our ci.

we clone our repo via something like:
```
git@github.com:org/repo.git
```

our ci job now fails during a `gh-pages` step with the following error:
```
Invalid URL: http:git@github.com:org/repo.git
```

**Pull request merged**
